server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/usuario/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/vehicle/**
        - id: sales-service
          uri: lb://sales-service
          predicates:
            - Path=/sales/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
